### ISSUE TITLE
Donor Homepage

### ISSUE THREAD

**Issue by meganniu** [uwblueprint/pregnancy-centre#14]
Deadline: March 4

Wireframes: [Figma](https://www.figma.com/file/ihFHz0IFltlXRHkXsd8xNH/Donor-Experience-Phase-1?node-id=387%3A79)
+ Final design finalized. This ticket will be updated with details (i.e. where to find the final design)
+ Link to final [design](https://www.figma.com/file/ihFHz0IFltlXRHkXsd8xNH/Donor-Experience-Phase-1?node-id=511%3A1373)

### Context
For the MVP of this project, we want to increase the visibility of open requests to donors. To ensure that donors are not biased by client requests, donors will only be able to see Request Groups and Request Types.

### Acceptance Criteria
* In the left panel, donors can view:
   * List of Request Groups in alphabetical order
   * A relevant picture
   * The number of open request groups
* Within a Request Group, donors can view:
   *  Item descriptions and requirements
   * The list of Request Types in alphabetical order
   * The number of open request types

Additional interactivity and behavior can be found on the final design figma link

### Tasks
Submit a separate PR for every task :) It'll be easier to review.
+ [x] Build RequestGroup graphql resolver + cache (@meganniu )
+ [x] Build RequestType graphql resolver + cache (@kevinwang2040 )
+ [x] Display list of all request groups on the left side (@meganniu )
  + List of request groups should be sorted alphabetically
+ [x] Display RequestGroup on right hand side when selected from list (@guy-ro)
  + Display all details for RequestGroup EXCEPT open requests
  + Details for RequestGroup: image, item description, requirements, etc.
+ [x] Display open requests for selected RequestGroup
  + List of requests should be sorted alphabetically

**Comment by meganniu** [comment]
Whoops this should not have been closed
