### ISSUE TITLE
Admin Sign Up

### ISSUE THREAD

**Issue by meganniu** [uwblueprint/pregnancy-centre#15]
Deadline: February 28

User schema: [Notion](https://www.notion.so/uwblueprintexecs/MongoDB-Schemas-577ae0f4beb34778b754b56853cdbbad#47b8d9e71bc54530af8dcd7ae860de68)
Wireframes: [Figma](https://www.figma.com/file/dcSbJOfK3Jg1gCpWOd6hAK/TPC-Employee-Experience%3A-Phase-1?node-id=1%3A588)
+ Contact Bonnie with design questions or drop them in #designer-babies channel

Some tasks might not be needed depending on your choice of auth service.

### Tasks
Submit a separate PR for every task :) It'll be easier to review.
+ [x] Investigate and decide on an auth services
  + Check out the [investigation](https://docs.google.com/document/d/1wzCuOc8cDqXNTezvAJ53hyWpEpy5WGw62c9V34xhLWs/edit) done so far.
  + All admin login/signup/password recovery use cases should be covered by the auth service.
  + Try to keep cost low. Service should have a free tier.
+ [x] (If needed) build ~~backend endpoint~~  service on frontend to:
  + Sign up for an account
    + Return an error if user email is not in the domain `pregnancycentre.ca`
    + password requirements:
       + 12 characters minimum
       + at least one lowercase letter
       + at least one uppercase letter
       + at least one number
       + at least one symbol
    + If user is valid:
      + create *unverified* user in ~~MongoDB~~ Firebase ~~and set `verify` to false~~ 
      + generate and add password salt to password (handled by Firebase)
  + AND send an email to the user with a confirmation link
+ [x] ~~(If needed) build backend endpoint to confirm an account~~
  + ~~Changes `verify` field of user to `true`~~ Account verified in Firebase upon clicking link sent in confirmation email
+ [x] Build signup modal
+ [x] Build account confirmation modal

### Context

For the MVP of this project, we want to make sure only TPC staff is able to edit the list of requests donors see for obvious reasons. We will do this enabling TPC staff to create admin accounts by signing up with @pregnanycentre.ca emails. 

In this phase, we will not be building any account based functionality for general visitors to the platform. That is to say, only TPC staff can and should be creating accounts

### Acceptance Criteria
* TPC staff can sign up by providing an email and password
* If the email provided already exists in the system, we show an "email already registered" error message
* If the password does not meet minimum security requirements in length/complexity, we also show an error message
* If the email does not belong to a @pregnancycentre.ca domain, we show an error message
* If the user tries to submit a form with incomplete information, we show an error message as well. 
* Users can preview the password they've typed by unhiding it.
* If all the above error checks pass, we move the user to a confirmation modal which communicates that a confirmation email is sent

Password complexity criteria
* 12 characters minimum
* at least one lowercase letter
* at least one uppercase letter
* at least one number
* at least one symbol
