### ISSUE TITLE
Admin Account Recovery

### ISSUE THREAD

**Issue by meganniu** [uwblueprint/pregnancy-centre#17]
User schema: [Notion](https://www.notion.so/uwblueprintexecs/MongoDB-Schemas-577ae0f4beb34778b754b56853cdbbad#47b8d9e71bc54530af8dcd7ae860de68)
Wireframes: [Figma](https://www.figma.com/file/dcSbJOfK3Jg1gCpWOd6hAK/TPC-Employee-Experience%3A-Phase-1?node-id=1%3A588)
+ Contact Bonnie with design questions or drop them in #designer-babies channel

### Description

Initiate password reset modal:
![Screenshot from 2021-03-16 12-20-19](https://user-images.githubusercontent.com/20423590/111343679-08eb2300-8652-11eb-886f-ed75cc150687.png)

Password reset email sent modal:
![Screenshot from 2021-03-16 12-21-15](https://user-images.githubusercontent.com/20423590/111343826-2f10c300-8652-11eb-9d3e-2ada4b2878ab.png)

Password reset modal:
![Screenshot from 2021-03-16 12-22-00](https://user-images.githubusercontent.com/20423590/111343946-4c459180-8652-11eb-91b4-defa729dc34b.png)

Password reset successful modal:
![Screenshot from 2021-03-16 12-22-05](https://user-images.githubusercontent.com/20423590/111343928-48197400-8652-11eb-9eef-6d90292dc25d.png)

Password criteria:
- 12 characters minimum
- at least one lowercase letter
- at least one uppercase letter
- at least one number
- at least one symbol

### Acceptance Criteria

- As a user, I can initiate resetting my password from the login page
- I can provide my email associated with my account, which after I confirm sends a reset link to my email inbox
- Using this link, I am sent to a password reset modal to create a new password
- If my password doesn't meet minimum complexity requirements, I am notified of it
- After successfully resetting the password, I am taken back to the login page

### Tasks
+ [ ] Initiate password reset modal
+ [x] Password reset email sent modal (@bonnie)
  + Create a file called `PasswordResetEmailSentModal.tsx` in `client/src/pages`
  + Copy `client/src/pages/EmailConfirmedModal.tsx` into `PasswordResetEmailSentModal.tsx`
  + Add route `/password-reset-email-sent` for `PasswordResetEmailSentModal.tsx`  in `App.tsx`
     + Run `npm run start` in `/client` and go to `localhost:3000/password-reset-email-sent` in your browser
     + You should see the modal you copied
  + Edit `PasswordResetEmailSentModal.tsx` to match wireframes
+ [ ] Password reset modal (@bonnie-chin)
  + Styling (due Apr 9)
  + Functionality to reset password (due Apr 11)
+ [ ] Password reset successful modal

**Comment by bonnie-chin** [comment]
LMAO yes I will contact myself 😤😤
