### ISSUE TITLE
Create GraphQL Mutation Endpoints

### ISSUE THREAD

**Issue by meganniu** [uwblueprint/pregnancy-centre#57]
### Tasks
Create:
+ requestGroup mutation resolver  (create, edit, deletion) @kevinwang2040 
  + [ ] createRequestGroup
  + [ ] updateRequestGroup
  + [ ] deleteRequestGroup
    + propagate delete to RequestTypes and Requests belonging to the RequestGroup
+ requestType mutation resolver (create, edit, deletion) @kevinwang2040 
  + [ ] createRequestType
    + create RequestType  should verify RequestType.requestGroup exists (mongoose might handle this, pls investigate)
  + [ ] updateRequestType
  + [ ] deleteRequestType
    + propagate delete to Requests belonging to the RequestType
    + mark `deleted` fields on nested Requests to true
    + do **not** move Requests to `RequestType.request.fulfilled`
  + [ ] add `requestGroup` field (id of parent) to `RequestType` model 
+ request mutation resolver (create, edit, deletion) @Anand-Issac 
  + [ ] createRequest
    + create Request  should verify Request.requestType exists (mongoose might handle this, pls investigate)
  + [ ] updateRequest
  + [ ] deleteRequest
  + [ ] add `requestType` field (id of parent) to `RequestGroup` model 
+ client mutation resolver (create, edit, deletion) @Anand-Issac 
  + [ ] createClient
  + [ ] updateClient
  + [ ] deleteClient
  + [ ] add `deleted` field to client model (`clientModel.ts`, `graphql/schema.ts`)

### Notes
1. Flow for updateRequest and updateRequestType:
+ update RequestType  object
+ add RequestType.id to new RequestGroup 's requestTypes array
  + regardless of if RequestType.requestGroup  has changed
+ remove RequestType.id from old RequestGroup 's requestTypes array
  + regardless of if RequestType.requestGroup  has changed
+ if either add or remove fails, then revert changes to RequestType.requestGroup , the old RequestGroup , and the new RequestGroup

2. `RequestType` has **three** arrays of Request IDs.

Pseudocode for handling the arrays on `RequestType`:
```
export default class RequestTypeDataSource extends CachedMongooseDataSource<RequestTypeDocument> {
  addElementToArray(arr,element){...} // add element to arr if element doesn't already exist in arr
  removeElementFromArray(arr, element){...} // remove element from arr if it exists in arr
  async addFufilledRequest(requestTypeId, requestId){
    requestType = find RequestType with requestTypeId
    addElementToArray(requestType.requests.fulfilled, requestId)  
  }
  async addDeletedRequest(requestTypeId, requestId){...}
  async addOpenRequest(requestTypeId, requestId){...}
  async deleteFufilledRequest(requestTypeId, requestId){
    requestType = find RequestType with requestTypeId
    removeElementFromArray(requestType.requests.fulfilled, requestId)  
  }
  async deleteDeletedRequest(requestTypeId, requestId){...}
  async deleteOpenRequest(requestTypeId, requestId){...}
}
```

3. Cannot use IDs that are not associated with any MongoDB documents 
+  You can't set the ID of a requestType/requestGroup for a request/requestType to be the ID of a document that doesn't yet exist.
  + it will silently fail and create the new request/requestType without the invalid ID
+ for create/update: 
  + before you link up a Request to a RequestType, the Request must be created first
  + before you link up a RequestType to a RequestGroup, the RequestType must be created first

**Comment by meganniu** [comment]
Not done yet
