### ISSUE TITLE
Set up secret-manager

### ISSUE THREAD

**Issue by meganniu** [uwblueprint/pregnancy-centre#6]
### Background
`secret-manager` stores project secrets (e.g. database passwords) in UWBlueprint's Hashcorp Vault. Github users that are part of UWBlueprint's Github org can authenticate and retrieve projects secrets through CLI.
`secret-manager` was developed by UWBlueprint's internal-tools team.

### Tasks
+ [ ] Set up `secret-manager` for `/client` and `/server`. 
  + [Set up instructions](https://www.notion.so/uwblueprintexecs/Secret-Management-2d5b59ef0987415e93ec951ce05bf03e)
+ [ ] Send Sherry Li your feedback about `secret-manager` set up 
+ [ ] Add a page in [our Notion](https://www.notion.so/uwblueprintexecs/Engineering-d4b263ea954f45708ff5a7c77c51b2cd) with helpful links/examples about using `secret-manager`
+ [ ] Do a demo of how to use `secret-manager` during weekly work session/standup
